# Generated by Django 5.2.6 on 2025-10-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='acgme_id',
        ),
        migrations.RemoveField(
            model_name='program',
            name='coordinator_user',
        ),
        migrations.RemoveField(
            model_name='program',
            name='director_user',
        ),
    ]
