# Generated by Django 3.2.25 on 2025-09-06 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0004_add_subcompetency_epa_manytomany'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('shift_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('private_comments', models.TextField(blank=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_given', to=settings.AUTH_USER_MODEL)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentEPA',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('entrustment_level', models.IntegerField(choices=[(1, 'I had to do it (Requires constant direct supervision)'), (2, 'I helped a lot (Requires considerable direct supervision)'), (3, 'I helped a little (Requires minimal direct supervision)'), (4, 'I needed to be there but did not help (Requires indirect supervision)'), (5, "I didn't need to be there at all (No supervision required)")])),
                ('what_went_well', models.TextField()),
                ('what_could_improve', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_epas', to='assessments.assessment')),
                ('epa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.epa')),
            ],
            options={
                'db_table': 'assessment_epas',
            },
        ),
        migrations.AddIndex(
            model_name='assessmentepa',
            index=models.Index(fields=['assessment', 'epa'], name='assessment__assessm_d9668d_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentepa',
            index=models.Index(fields=['epa', 'entrustment_level'], name='assessment__epa_id_5c3a67_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentepa',
            index=models.Index(fields=['entrustment_level'], name='assessment__entrust_4b88ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentepa',
            unique_together={('assessment', 'epa')},
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['trainee', 'shift_date'], name='assessments_trainee_c3f7e2_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['evaluator', 'created_at'], name='assessments_evaluat_cf5deb_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['status', 'created_at'], name='assessments_status_2e0d62_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['shift_date'], name='assessments_shift_d_6917d3_idx'),
        ),
    ]
