# Generated by Django 5.2.6 on 2025-09-18 22:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_auto_20250906_1727'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentMailboxRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_reads', to='assessments.assessment')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_mailbox_reads',
                'indexes': [models.Index(fields=['assessment', 'reader'], name='assessment__assessm_3b86f3_idx'), models.Index(fields=['reader', 'read_at'], name='assessment__reader__43e51d_idx')],
                'unique_together': {('assessment', 'reader')},
            },
        ),
    ]
