# Generated by Django 5.2.6 on 2025-09-18 22:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_add_mailbox_read_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='acknowledged_at',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='acknowledged_by',
        ),
        migrations.DeleteModel(
            name='AssessmentMailboxRead',
        ),
        migrations.AddField(
            model_name='assessment',
            name='acknowledged_by',
            field=models.ManyToManyField(blank=True, help_text='Leadership users who have acknowledged this assessment', related_name='assessments_acknowledged', to=settings.AUTH_USER_MODEL),
        ),
    ]
