# Generated by Django 5.2.6 on 2025-09-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_personalized_leadership_mailbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentepa',
            name='what_could_improve',
        ),
        migrations.RemoveField(
            model_name='assessmentepa',
            name='what_went_well',
        ),
        migrations.AddField(
            model_name='assessment',
            name='what_could_improve',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='what_went_well',
            field=models.TextField(blank=True),
        ),
    ]
