# Generated by Django 3.2.25 on 2025-09-02 22:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreCompetency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Core Competencies',
                'db_table': 'core_competencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EPA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'epas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EPACategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'EPA Categories',
                'db_table': 'epa_categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SubCompetency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('milestone_level_1', models.TextField()),
                ('milestone_level_2', models.TextField()),
                ('milestone_level_3', models.TextField()),
                ('milestone_level_4', models.TextField()),
                ('milestone_level_5', models.TextField()),
                ('core_competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_competencies', to='curriculum.corecompetency')),
                ('epa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_competencies', to='curriculum.epa')),
            ],
            options={
                'verbose_name_plural': 'Sub Competencies',
                'db_table': 'sub_competencies',
                'ordering': ['code'],
            },
        ),
    ]
