# Generated by Django 3.2.25 on 2025-09-02 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcompetency',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_competencies', to='organizations.program'),
        ),
        migrations.AddField(
            model_name='epacategory',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epa_categories', to='organizations.program'),
        ),
        migrations.AddField(
            model_name='epa',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epas', to='curriculum.epacategory'),
        ),
        migrations.AddField(
            model_name='epa',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epas', to='organizations.program'),
        ),
        migrations.AddField(
            model_name='corecompetency',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_competencies', to='organizations.program'),
        ),
        migrations.AlterUniqueTogether(
            name='epa',
            unique_together={('program', 'code')},
        ),
    ]
