# Generated by Django 3.2.25 on 2025-09-05 22:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_make_epa_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcompetency',
            name='epa',
        ),
        migrations.CreateModel(
            name='SubCompetencyEPA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_competency_epas', to='curriculum.epa')),
                ('sub_competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_competency_epas', to='curriculum.subcompetency')),
            ],
            options={
                'db_table': 'sub_competency_epas',
                'unique_together': {('sub_competency', 'epa')},
            },
        ),
        migrations.AddField(
            model_name='subcompetency',
            name='epas',
            field=models.ManyToManyField(related_name='sub_competencies', through='curriculum.SubCompetencyEPA', to='curriculum.EPA'),
        ),
    ]
