# Generated by Django 5.2.6 on 2025-09-29 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_add_subcompetency_epa_manytomany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epa',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epas', to='curriculum.epacategory'),
        ),
        migrations.AlterField(
            model_name='epa',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
