services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    ports:
      - "8001:8000"
    environment:
      - DEBUG=0
      - DATABASE_URL=sqlite:///db.sqlite3
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./logs:/app/logs
      - ./static:/app/staticfiles
    restart: unless-stopped
