# Generated by Django 3.2.25 on 2025-09-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
        ('users', '0003_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='programs',
            field=models.ManyToManyField(blank=True, help_text='Programs this faculty member is associated with', related_name='faculty', to='organizations.Program'),
        ),
    ]
