# Generated by Django 5.2.6 on 2025-09-14 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
        ('users', '0004_user_programs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='programs',
        ),
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Program this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organizations.program'),
        ),
    ]
