# Generated by Django 5.2.6 on 2025-09-18 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_deactivated_at_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cohort',
            field=models.ForeignKey(blank=True, help_text='Cohort this user belongs to (required for trainees)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.cohort'),
        ),
    ]
