# Generated by Django 5.2.6 on 2025-11-30 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_cohort_options_alter_cohort_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('success', models.BooleanField(help_text='Whether the login attempt was successful')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the login attempt', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for login failure (if applicable)', max_length=200)),
                ('user', models.ForeignKey(blank=True, help_text='The user who attempted to login (null if user not found)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_attempts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email', '-timestamp'], name='login_attem_email_d532d7_idx'), models.Index(fields=['user', '-timestamp'], name='login_attem_user_id_6a7006_idx'), models.Index(fields=['-timestamp'], name='login_attem_timesta_02f426_idx'), models.Index(fields=['success', '-timestamp'], name='login_attem_success_22e1ce_idx')],
            },
        ),
    ]
